apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy-deployment-ha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mitmproxy-ha
  template:
    metadata:
      labels:
        app: mitmproxy-ha
    spec:
      containers:
      - name: mitmproxy-ha
        image: demoacrcn.azurecr.cn/mitmproxy:v25
        volumeMounts:
        - name: mitmproxy-volume
          mountPath: /app
        env:
        - name: AZURE_AD_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-ad-secret
              key: tenant-id
        - name: AZURE_AD_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-ad-secret
              key: client-id
        - name: AZURE_AD_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-ad-secret
              key: client-secret
      volumes:
      - name: mitmproxy-volume
        persistentVolumeClaim:
          claimName: mitmproxy-pvc
