apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitmproxy-deployment-ha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mitmproxy-ha
  template:
    metadata:
      labels:
        app: mitmproxy-ha
    spec:
      containers:
      - name: mitmproxy-ha
        image: demoacrcn.azurecr.cn/mitmproxy:v25
        volumeMounts:
        - name: mitmproxy-volume
          mountPath: /app
        env:
        - name: TENANT_ID
          value: "your_tenant_id"
        - name: CLIENT_ID
          value: "your_client_id"
        - name: CLIENT_SECRET
          value: "your_client_secret"
      volumes:
      - name: mitmproxy-volume
        persistentVolumeClaim:
          claimName: mitmproxy-pvc
